pair: "ETHUSDT"
scenario: "CEX_BUY_DEX_SELL"
mode: "real"
dry_run: true

mexc:
  api_key: "YOUR_MEXC_KEY"
  api_secret: "YOUR_MEXC_SECRET"
  rest_url: "https://api.mexc.com"
  ws_url: "wss://wbs-api.mexc.com/ws"
  withdrawal_fee_base: 0.0012
  taker_fee_bps: 5

redis:
  addr: "127.0.0.1:6379"
  db: 0
  username: ""
  password: ""
  stream: "book:stream"
  pubchan: "book:pub"   # если захочешь Pub/Sub
  active_key: "book:active"
  snap_ns: "book:snap:" # префикс для HASH-ов


chain:
  network: "arbitrum-one"
  rpc_http: "https://arb1.arbitrum.io/rpc"         # HTTP RPC Arbitrum One
  rpc_ws:   "wss://arb1.arbitrum.io/ws"            # WS RPC (если используешь)
  wallet_pk: ""                                    # твой приватный ключ (hex, без 0x)
  max_priority_fee_gwei: 0.1                       # на Arbitrum обычно маленький tip
  gas_limit_swap: 180000

dex:
  # Внимание: адреса для ARBITRUM ONE
  weth: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"   # WETH (Arbitrum)
  usdt: "0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9"   # USDT (Arbitrum)
  fee_tiers: [500, 3000]                               # какие тиров проверять
  quoter_v1: ""                                        # V1 можно не использовать на Arbitrum
  quoter_v2: "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"  # Uniswap V3 QuoterV2 (Arbitrum)
  multicall: "0xCa11bde05977b3631167028862bE2a173976CA11"
risk:
  max_slippage_bps: 50
  min_profit_usd: 8
  min_roi_bps: 10
  max_gas_usd: 10
  min_fill_ratio: 0.7

trade:
  base_qty: 1

metrics:
  listen_addr: ":9090"

timings:
  quote_interval_ms: 300
  detector_tick_ms: 150
