// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: PublicMiniTickersV3Api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicMiniTickersV3Api struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Items         []*PublicMiniTickersV3Api_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicMiniTickersV3Api) Reset() {
	*x = PublicMiniTickersV3Api{}
	mi := &file_PublicMiniTickersV3Api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicMiniTickersV3Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicMiniTickersV3Api) ProtoMessage() {}

func (x *PublicMiniTickersV3Api) ProtoReflect() protoreflect.Message {
	mi := &file_PublicMiniTickersV3Api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicMiniTickersV3Api.ProtoReflect.Descriptor instead.
func (*PublicMiniTickersV3Api) Descriptor() ([]byte, []int) {
	return file_PublicMiniTickersV3Api_proto_rawDescGZIP(), []int{0}
}

func (x *PublicMiniTickersV3Api) GetItems() []*PublicMiniTickersV3Api_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type PublicMiniTickersV3Api_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // => it.GetSymbol()
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`   // => it.GetPrice()
	Volume        string                 `protobuf:"bytes,3,opt,name=volume,proto3" json:"volume,omitempty"` // => it.GetVolume()
	High          string                 `protobuf:"bytes,4,opt,name=high,proto3" json:"high,omitempty"`     // (опц.) it.GetHigh()
	Low           string                 `protobuf:"bytes,5,opt,name=low,proto3" json:"low,omitempty"`       // (опц.) it.GetLow()
	Rate          string                 `protobuf:"bytes,6,opt,name=rate,proto3" json:"rate,omitempty"`     // (опц.) it.GetRate() — 24h change rate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicMiniTickersV3Api_Item) Reset() {
	*x = PublicMiniTickersV3Api_Item{}
	mi := &file_PublicMiniTickersV3Api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicMiniTickersV3Api_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicMiniTickersV3Api_Item) ProtoMessage() {}

func (x *PublicMiniTickersV3Api_Item) ProtoReflect() protoreflect.Message {
	mi := &file_PublicMiniTickersV3Api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicMiniTickersV3Api_Item.ProtoReflect.Descriptor instead.
func (*PublicMiniTickersV3Api_Item) Descriptor() ([]byte, []int) {
	return file_PublicMiniTickersV3Api_proto_rawDescGZIP(), []int{1}
}

func (x *PublicMiniTickersV3Api_Item) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PublicMiniTickersV3Api_Item) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PublicMiniTickersV3Api_Item) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *PublicMiniTickersV3Api_Item) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *PublicMiniTickersV3Api_Item) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *PublicMiniTickersV3Api_Item) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

var File_PublicMiniTickersV3Api_proto protoreflect.FileDescriptor

const file_PublicMiniTickersV3Api_proto_rawDesc = "" +
	"\n" +
	"\x1cPublicMiniTickersV3Api.proto\x12\x02pb\"O\n" +
	"\x16PublicMiniTickersV3Api\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.pb.PublicMiniTickersV3Api_ItemR\x05items\"\x9d\x01\n" +
	"\x1bPublicMiniTickersV3Api_Item\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\tR\x06volume\x12\x12\n" +
	"\x04high\x18\x04 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\tR\x03low\x12\x12\n" +
	"\x04rate\x18\x06 \x01(\tR\x04rateB;Z9github.com/you/arb-bot/internal/connectors/cex/mexc/pb;pbb\x06proto3"

var (
	file_PublicMiniTickersV3Api_proto_rawDescOnce sync.Once
	file_PublicMiniTickersV3Api_proto_rawDescData []byte
)

func file_PublicMiniTickersV3Api_proto_rawDescGZIP() []byte {
	file_PublicMiniTickersV3Api_proto_rawDescOnce.Do(func() {
		file_PublicMiniTickersV3Api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PublicMiniTickersV3Api_proto_rawDesc), len(file_PublicMiniTickersV3Api_proto_rawDesc)))
	})
	return file_PublicMiniTickersV3Api_proto_rawDescData
}

var file_PublicMiniTickersV3Api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_PublicMiniTickersV3Api_proto_goTypes = []any{
	(*PublicMiniTickersV3Api)(nil),      // 0: pb.PublicMiniTickersV3Api
	(*PublicMiniTickersV3Api_Item)(nil), // 1: pb.PublicMiniTickersV3Api_Item
}
var file_PublicMiniTickersV3Api_proto_depIdxs = []int32{
	1, // 0: pb.PublicMiniTickersV3Api.items:type_name -> pb.PublicMiniTickersV3Api_Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PublicMiniTickersV3Api_proto_init() }
func file_PublicMiniTickersV3Api_proto_init() {
	if File_PublicMiniTickersV3Api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PublicMiniTickersV3Api_proto_rawDesc), len(file_PublicMiniTickersV3Api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PublicMiniTickersV3Api_proto_goTypes,
		DependencyIndexes: file_PublicMiniTickersV3Api_proto_depIdxs,
		MessageInfos:      file_PublicMiniTickersV3Api_proto_msgTypes,
	}.Build()
	File_PublicMiniTickersV3Api_proto = out.File
	file_PublicMiniTickersV3Api_proto_goTypes = nil
	file_PublicMiniTickersV3Api_proto_depIdxs = nil
}
