global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "arb-bot"
    static_configs:
      - targets:
          # Бот поднимает метрики на :9090 (см. логи "metrics server starting :9090")
          # В контейнере достучимся так:
          - host.docker.internal:9090
